#!/usr/bin/env pwsh
#Requires -Version 7.0
<#
.SYNOPSIS
  Configure Kanbanize / Businessmap credentials for Cursor agents.

.DESCRIPTION
  Reads credentials from the environment, validates them against the
  Businessmap API v2, and writes local config under ~/.config/kanbanize
  (or $XDG_CONFIG_HOME/kanbanize).

  Required:
    KANBANIZE_API_KEY          API key from My Account → API
                               (alias: BUSINESSMAP_API_TOKEN)

  Optional:
    KANBANIZE_SUBDOMAIN        Account subdomain (default: grupoboticario)
    KANBANIZE_API_URL          Full API base URL
                               (default: https://<subdomain>.kanbanize.com/api/v2)
    BUSINESSMAP_READ_ONLY_MODE true|false (default: false)
    BUSINESSMAP_TOOL_PROFILE   essential|standard|full|minimal (default: essential)
    BUSINESSMAP_DEFAULT_WORKSPACE_ID
    KANBANIZE_INSTALL_MCP      If "1" or "true", install @edicarlos.lds/businessmap-mcp globally

.EXAMPLE
  pwsh -NoProfile -File ~/.config/kanbanize/setup.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Step([string]$Message) {
    Write-Host "==> $Message" -ForegroundColor Cyan
}

function Write-Ok([string]$Message) {
    Write-Host "OK  $Message" -ForegroundColor Green
}

function Write-Warn([string]$Message) {
    Write-Host "!!  $Message" -ForegroundColor Yellow
}

function Get-ConfigDir {
    if ($env:XDG_CONFIG_HOME) {
        return (Join-Path $env:XDG_CONFIG_HOME 'kanbanize')
    }
    return (Join-Path $HOME '.config/kanbanize')
}

function Resolve-ApiKey {
    $candidates = @(
        @(
            $env:KANBANIZE_API_KEY,
            $env:BUSINESSMAP_API_TOKEN,
            $env:KANBANIZE_API_TOKEN
        ) | Where-Object { $_ -and $_.ToString().Trim().Length -gt 0 }
    )

    if ($candidates.Count -eq 0) {
        throw @"
Missing API key. Set one of:
  KANBANIZE_API_KEY
  BUSINESSMAP_API_TOKEN
"@
    }
    return $candidates[0].ToString().Trim()
}

function Resolve-ApiUrl([string]$ApiKey) {
    if ($env:KANBANIZE_API_URL -and $env:KANBANIZE_API_URL.Trim()) {
        return $env:KANBANIZE_API_URL.Trim().TrimEnd('/')
    }
    if ($env:BUSINESSMAP_API_URL -and $env:BUSINESSMAP_API_URL.Trim()) {
        return $env:BUSINESSMAP_API_URL.Trim().TrimEnd('/')
    }

    $subdomain = if ($env:KANBANIZE_SUBDOMAIN -and $env:KANBANIZE_SUBDOMAIN.Trim()) {
        $env:KANBANIZE_SUBDOMAIN.Trim()
    } else {
        'grupoboticario'
    }

    return "https://$subdomain.kanbanize.com/api/v2"
}

function Test-KanbanizeConnection([string]$ApiUrl, [string]$ApiKey) {
    $uri = "$ApiUrl/me"
    Write-Step "Validating API at $uri"

    $headers = @{
        apikey = $ApiKey
        Accept = 'application/json'
    }

    try {
        $response = Invoke-RestMethod -Method Get -Uri $uri -Headers $headers -TimeoutSec 30
    } catch {
        throw "Kanbanize API validation failed: $($_.Exception.Message)"
    }

    if (-not $response.data) {
        throw "Unexpected /me response (missing data)."
    }

    return $response.data
}

function Write-EnvFile([string]$Path, [hashtable]$Values) {
    $lines = @(
        '# Generated by kanbanize/setup.ps1 — do not commit'
    )
    foreach ($key in ($Values.Keys | Sort-Object)) {
        $lines += "$key=$($Values[$key])"
    }
    Set-Content -Path $Path -Value $lines -Encoding utf8
}

function Install-BusinessmapMcp {
    if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
        Write-Warn 'npm not found; skipping Businessmap MCP install'
        return
    }

    $prefix = Join-Path $HOME '.npm-global'
    New-Item -ItemType Directory -Force -Path $prefix | Out-Null
    $env:NPM_CONFIG_PREFIX = $prefix
    $binDir = Join-Path $prefix 'bin'
    $pathSep = [IO.Path]::PathSeparator
    if (($env:PATH -split [regex]::Escape($pathSep)) -notcontains $binDir) {
        $env:PATH = "${binDir}${pathSep}$($env:PATH)"
    }

    Write-Step "Installing @edicarlos.lds/businessmap-mcp into $prefix"
    & npm install -g '--prefix' $prefix '@edicarlos.lds/businessmap-mcp'
    if ($LASTEXITCODE -ne 0) {
        throw "npm install failed with exit code $LASTEXITCODE"
    }

    if (-not (Get-Command businessmap-mcp -ErrorAction SilentlyContinue)) {
        Write-Warn "businessmap-mcp binary not on PATH yet; add $binDir to PATH"
    } else {
        Write-Ok 'businessmap-mcp installed'
    }
}

$configDir = Get-ConfigDir
New-Item -ItemType Directory -Force -Path $configDir | Out-Null

$apiKey = Resolve-ApiKey
$apiUrl = Resolve-ApiUrl $apiKey
$me = Test-KanbanizeConnection -ApiUrl $apiUrl -ApiKey $apiKey

$readOnly = if ($env:BUSINESSMAP_READ_ONLY_MODE) { $env:BUSINESSMAP_READ_ONLY_MODE } else { 'false' }
$toolProfile = if ($env:BUSINESSMAP_TOOL_PROFILE) { $env:BUSINESSMAP_TOOL_PROFILE } else { 'essential' }
$defaultWorkspace = $env:BUSINESSMAP_DEFAULT_WORKSPACE_ID

$config = [ordered]@{
    subdomain     = ([uri]$apiUrl).Host.Split('.')[0]
    api_url       = $apiUrl
    user_id       = $me.user_id
    email         = $me.email
    username      = $me.username
    realname      = $me.realname
    read_only     = $readOnly
    tool_profile  = $toolProfile
    configured_at = (Get-Date).ToUniversalTime().ToString('o')
}

if ($defaultWorkspace) {
    $config['default_workspace_id'] = $defaultWorkspace
}

$configPath = Join-Path $configDir 'config.json'
$envPath = Join-Path $configDir '.env'
$mcpSnippetPath = Join-Path $configDir 'mcp.snippet.json'

# Persist non-secret metadata
$config | ConvertTo-Json -Depth 5 | Set-Content -Path $configPath -Encoding utf8
Write-Ok "Wrote $configPath"

# Persist secrets for local MCP / CLI (mode 600 when chmod exists)
$envValues = @{
    KANBANIZE_API_KEY        = $apiKey
    BUSINESSMAP_API_TOKEN    = $apiKey
    BUSINESSMAP_API_URL      = $apiUrl
    BUSINESSMAP_READ_ONLY_MODE = $readOnly
    BUSINESSMAP_TOOL_PROFILE = $toolProfile
}
if ($defaultWorkspace) {
    $envValues['BUSINESSMAP_DEFAULT_WORKSPACE_ID'] = $defaultWorkspace
}
Write-EnvFile -Path $envPath -Values $envValues

if (Get-Command chmod -ErrorAction SilentlyContinue) {
    & chmod 600 $envPath
}
Write-Ok "Wrote $envPath (secrets, mode 600)"

$mcpSnippet = @{
    mcpServers = @{
        businessmap = @{
            command = 'npx'
            args    = @('-y', '@edicarlos.lds/businessmap-mcp')
            env     = @{
                BUSINESSMAP_API_TOKEN      = '${KANBANIZE_API_KEY}'
                BUSINESSMAP_API_URL        = $apiUrl
                BUSINESSMAP_READ_ONLY_MODE = $readOnly
                BUSINESSMAP_TOOL_PROFILE   = $toolProfile
            }
        }
    }
}
if ($defaultWorkspace) {
    $mcpSnippet.mcpServers.businessmap.env.BUSINESSMAP_DEFAULT_WORKSPACE_ID = $defaultWorkspace
}
$mcpSnippet | ConvertTo-Json -Depth 8 | Set-Content -Path $mcpSnippetPath -Encoding utf8
Write-Ok "Wrote $mcpSnippetPath"

$installMcp = $env:KANBANIZE_INSTALL_MCP
if ($installMcp -in @('1', 'true', 'True', 'TRUE', 'yes', 'YES')) {
    Install-BusinessmapMcp
}

# Copy this script into the config dir when run from the repo
$selfPath = $MyInvocation.MyCommand.Path
$targetScript = Join-Path $configDir 'setup.ps1'
if ($selfPath -and (Test-Path $selfPath) -and ($selfPath -ne $targetScript)) {
    Copy-Item -Path $selfPath -Destination $targetScript -Force
    Write-Ok "Installed launcher at $targetScript"
}

Write-Host ''
Write-Host 'Kanbanize setup complete' -ForegroundColor Green
Write-Host ("  User:      {0} <{1}>" -f $me.realname, $me.email)
Write-Host ("  Username:  {0} (id {1})" -f $me.username, $me.user_id)
Write-Host ("  API URL:   {0}" -f $apiUrl)
Write-Host ("  Config:    {0}" -f $configDir)
Write-Host ''
Write-Host 'Re-run anytime with:'
Write-Host '  pwsh -NoProfile -File ~/.config/kanbanize/setup.ps1'
